db.getCollection('catalogs')
  .drop();
db.getCollection('catalogs')
  .insertMany([
    {
      _id: 'home',
      name: 'Головна',
      ancestors: [],
      parent: null,
      scrollableForIds: [],
      auth: 'casual',
      order: 0,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'common',
      name: 'Загальні',
      ancestors: [],
      parent: 'home',
      scrollableForIds: [],
      auth: 'casual',
      order: 0,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'system',
      name: 'Системні',
      ancestors: [],
      parent: 'home',
      scrollableForIds: [],
      auth: 'guest',
      order: 0,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'products',
      name: 'Продукти',
      ancestors: ['home', 'common'],
      parent: 'common',
      scrollableForIds: [],
      auth: 'casual',
      order: 0,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'tecnology',
      name: 'Технологія',
      ancestors: ['home', 'common'],
      parent: 'common',
      scrollableForIds: ['common'],
      auth: 'casual',
      order: 3,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'delivery',
      name: 'Доставка і оплата',
      ancestors: ['home'],
      parent: 'common',
      scrollableForIds: [],
      auth: 'casual',
      order: 0,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'feedback',
      name: 'Зворотній звязок',
      ancestors: ['home', 'common'],
      parent: 'common',
      scrollableForIds: ['common'],
      auth: 'casual',
      order: 4,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'cart',
      name: 'Корзина',
      ancestors: ['home', 'common'],
      parent: 'common',
      scrollableForIds: [],
      auth: 'casual',
      order: 0,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'profile',
      name: 'Профіль',
      ancestors: ['home', 'system'],
      parent: 'system',
      scrollableForIds: [],
      auth: 'casual',
      order: 0,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'Plankit',
      name: 'Plankit',
      ancestors: ['home', 'common', 'products'],
      parent: 'products',
      scrollableForIds: ['common', 'products'],
      auth: 'casual',
      order: 1,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'Domino SPC',
      name: 'Domino SPC',
      ancestors: ['home', 'common', 'products'],
      parent: 'products',
      scrollableForIds: ['common', 'products'],
      auth: 'casual',
      order: 2,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
    {
      _id: 'dashboard',
      name: 'Dashboard',
      ancestors: [],
      parent: 'system',
      scrollableForIds: [],
      auth: 'guest',
      order: 0,
      picture: '',
      description: '',
      prefix: '',
      seoTitle: '',
      seoMeta: '',
    },
  ]);
